Songul_Kosak_211103058/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Songul_Kosak_211103058.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult FileUpload()
        {
            return View();
        }
        [HttpPost]
        public ActionResult FileUpload(HttpPostedFileBase file)
        {
            if(file != null && file.ContentLength > 0)
            {
                string path = Path.Combine(Server.MapPath("~/UploadedFiles"),Path.GetFileName(file.FileName));
                file.SaveAs(path);
                ViewBag.Mesaj = "/UploadedFiles/" + file.FileName;
            }
            
            return View();
        }
    }
}

Songul_Kosak_211103058/Controllers/AnasayfaYonetimController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Songul_Kosak_211103058.DAL;

namespace Songul_Kosak_211103058.Controllers
{
    public class AnasayfaYonetimController : Controller
    {
        private DatabaseModel db = new DatabaseModel();

        // GET: AnasayfaYonetim
        public ActionResult Index()
        {
            return View(db.Anasayfa.ToList());
        }

        // GET: AnasayfaYonetim/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Anasayfa anasayfa = db.Anasayfa.Find(id);
            if (anasayfa == null)
            {
                return HttpNotFound();
            }
            return View(anasayfa);
        }

        // GET: AnasayfaYonetim/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AnasayfaYonetim/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AnasayfaId,UstResimYolu,OrtaBaslik,AraResim,BizKimizYazisi,BizKimizBaslik,ButonYazi,AltResimYolu,AltResimBaslik,AltResimYazi")] Anasayfa anasayfa)
        {
            if (ModelState.IsValid)
            {
                db.Anasayfa.Add(anasayfa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(anasayfa);
        }

        // GET: AnasayfaYonetim/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Anasayfa anasayfa = db.Anasayfa.Find(id);
            if (anasayfa == null)
            {
                return HttpNotFound();
            }
            return View(anasayfa);
        }

        // POST: AnasayfaYonetim/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AnasayfaId,UstResimYolu,OrtaBaslik,AraResim,BizKimizYazisi,BizKimizBaslik,ButonYazi,AltResimYolu,AltResimBaslik,AltResimYazi")] Anasayfa anasayfa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(anasayfa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(anasayfa);
        }

        // GET: AnasayfaYonetim/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Anasayfa anasayfa = db.Anasayfa.Find(id);
            if (anasayfa == null)
            {
                return HttpNotFound();
            }
            return View(anasayfa);
        }

        // POST: AnasayfaYonetim/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Anasayfa anasayfa = db.Anasayfa.Find(id);
            db.Anasayfa.Remove(anasayfa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Songul_Kosak_211103058/Controllers/IletisimYonetimController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Songul_Kosak_211103058.DAL;

namespace Songul_Kosak_211103058.Controllers
{
    public class IletisimYonetimController : Controller
    {
        private DatabaseModel db = new DatabaseModel();

        // GET: IletisimYonetim
        public ActionResult Index()
        {
            return View(db.Iletisim.ToList());
        }

        // GET: IletisimYonetim/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Iletisim iletisim = db.Iletisim.Find(id);
            if (iletisim == null)
            {
                return HttpNotFound();
            }
            return View(iletisim);
        }

        // GET: IletisimYonetim/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: IletisimYonetim/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IletisimId,AdresBaslik,BaslikBilgi,BizeUlasinYazisi,AdresSatir1,AdresSatir2,AdresSatir3,Tel1,Tel2")] Iletisim iletisim)
        {
            if (ModelState.IsValid)
            {
                db.Iletisim.Add(iletisim);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(iletisim);
        }

        // GET: IletisimYonetim/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Iletisim iletisim = db.Iletisim.Find(id);
            if (iletisim == null)
            {
                return HttpNotFound();
            }
            return View(iletisim);
        }

        // POST: IletisimYonetim/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IletisimId,AdresBaslik,BaslikBilgi,BizeUlasinYazisi,AdresSatir1,AdresSatir2,AdresSatir3,Tel1,Tel2")] Iletisim iletisim)
        {
            if (ModelState.IsValid)
            {
                db.Entry(iletisim).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(iletisim);
        }

        // GET: IletisimYonetim/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Iletisim iletisim = db.Iletisim.Find(id);
            if (iletisim == null)
            {
                return HttpNotFound();
            }
            return View(iletisim);
        }

        // POST: IletisimYonetim/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Iletisim iletisim = db.Iletisim.Find(id);
            db.Iletisim.Remove(iletisim);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Songul_Kosak_211103058/Controllers/LensYonetimController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Songul_Kosak_211103058.DAL;

namespace Songul_Kosak_211103058.Controllers
{
    public class LensYonetimController : Controller
    {
        private DatabaseModel db = new DatabaseModel();

        // GET: LensYonetim
        public ActionResult Index()
        {
            return View(db.Lens.ToList());
        }

        // GET: LensYonetim/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lens lens = db.Lens.Find(id);
            if (lens == null)
            {
                return HttpNotFound();
            }
            return View(lens);
        }

        // GET: LensYonetim/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LensYonetim/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LensId,LensResimYolu,LensÜstYazi,ResimSira")] Lens lens)
        {
            if (ModelState.IsValid)
            {
                db.Lens.Add(lens);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(lens);
        }

        // GET: LensYonetim/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lens lens = db.Lens.Find(id);
            if (lens == null)
            {
                return HttpNotFound();
            }
            return View(lens);
        }

        // POST: LensYonetim/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LensId,LensResimYolu,LensÜstYazi,ResimSira")] Lens lens)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lens).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lens);
        }

        // GET: LensYonetim/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lens lens = db.Lens.Find(id);
            if (lens == null)
            {
                return HttpNotFound();
            }
            return View(lens);
        }

        // POST: LensYonetim/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Lens lens = db.Lens.Find(id);
            db.Lens.Remove(lens);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Songul_Kosak_211103058/Views/Shared/_LayoutPageAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/style-coblocks-19079.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>

    <style>
        @@import url('https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css');
@@media(min-width:768px) {
    body {
        margin-top: 50px;
    }
    /*html, body, #wrapper, #page-wrapper {height: 100%; overflow: hidden;}*/
}

#wrapper {
    padding-left: 0;
}

#page-wrapper {
    width: 100%;
    padding: 0;
    background-color: #fff;
}

@@media(min-width:768px) {
    #wrapper {
        padding-left: 225px;
    }

    #page-wrapper {
        padding: 22px 10px;
    }
}

/* Top Navigation */

.top-nav {
    padding: 0 15px;
}

.top-nav>li {
    display: inline-block;
    float: left;
}

.top-nav>li>a {
    padding-top: 20px;
    padding-bottom: 20px;
    line-height: 20px;
    color: #fff;
}

.top-nav>li>a:hover,
.top-nav>li>a:focus,
.top-nav>.open>a,
.top-nav>.open>a:hover,
.top-nav>.open>a:focus {
    color: #fff;
    background-color: #1a242f;
}

.top-nav>.open>.dropdown-menu {
    float: left;
    position: absolute;
    margin-top: 0;
    /*border: 1px solid rgba(0,0,0,.15);*/
    border-top-left-radius: 0;
    border-top-right-radius: 0;
    background-color: #fff;
    -webkit-box-shadow: 0 6px 12px rgba(0,0,0,.175);
    box-shadow: 0 6px 12px rgba(0,0,0,.175);
}

.top-nav>.open>.dropdown-menu>li>a {
    white-space: normal;
}

/* Side Navigation */

@@media(min-width:768px) {
    .side-nav {
        position: fixed;
        top: 60px;
        left: 225px;
        width: 225px;
        margin-left: -225px;
        border: none;
        border-radius: 0;
        border-top: 1px rgba(0,0,0,.5) solid;
        overflow-y: auto;
        background-color: #222;
        /*background-color: #5A6B7D;*/
        bottom: 0;
        overflow-x: hidden;
        padding-bottom: 40px;
    }

    .side-nav>li>a {
        width: 225px;
        border-bottom: 1px rgba(0,0,0,.3) solid;
    }

    .side-nav li a:hover,
    .side-nav li a:focus {
        outline: none;
        background-color: #1a242f !important;
    }
}

.side-nav>li>ul {
    padding: 0;
    border-bottom: 1px rgba(0,0,0,.3) solid;
}

.side-nav>li>ul>li>a {
    display: block;
    padding: 10px 15px 10px 38px;
    text-decoration: none;
    /*color: #999;*/
    color: #fff;
}

.side-nav>li>ul>li>a:hover {
    color: #fff;
}

.navbar .nav > li > a > .label {
  -webkit-border-radius: 50%;
  -moz-border-radius: 50%;
  border-radius: 50%;
  position: absolute;
  top: 14px;
  right: 6px;
  font-size: 10px;
  font-weight: normal;
  min-width: 15px;
  min-height: 15px;
  line-height: 1.0em;
  text-align: center;
  padding: 2px;
}

.navbar .nav > li > a:hover > .label {
  top: 10px;
}

.navbar-brand {
    padding: 5px 15px;
}
    </style>

</head>
<body>

    <div id="throbber" style="display:none; min-height:120px;"></div>
    <div id="noty-holder"></div>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="https://bryanrojasq.wordpress.com">
                    <img src="~/Content/icons8-admin-settings-male-50 (1).png" alt="LOGO">
                </a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li>
                    <a href="#" data-placement="bottom" data-toggle="tooltip" href="#" data-original-title="Stats">
                        <i class="fa fa-bar-chart-o"></i>
                    </a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Yönetici Kullanıcı <b class="fa fa-angle-down"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#"><i class="fa fa-fw fa-user"></i> Edit Profile</a></li>
                        <li><a href="#"><i class="fa fa-fw fa-cog"></i> Change Password</a></li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="fa fa-fw fa-power-off"></i> Logout</a></li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    @*<li>
            <a href="#" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-fw fa-search"></i> MENU 1 <i class="fa fa-fw fa-angle-down pull-right"></i></a>
            <ul id="submenu-1" class="collapse">
                <li><a href="#"><i class="fa fa-angle-double-right"></i> SUBMENU 1.1</a></li>
                <li><a href="#"><i class="fa fa-angle-double-right"></i> SUBMENU 1.2</a></li>
                <li><a href="#"><i class="fa fa-angle-double-right"></i> SUBMENU 1.3</a></li>
            </ul>
        </li>*@
                    <li>
                        <a href="@Url.Action("Index","MarkalarimizYonetim")"><i class="fa fa-fw fa-user-plus"></i>  Marka Yönetimi </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","LensYonetim")"><i class="fa fa-fw fa-paper-plane-o"></i> Lens Yönetimi </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","IletisimYonetim")"><i class="fa fa-fw fa fa-question-circle"></i> İletisim Yönetimi </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","AnasayfaYonetim")"><i class="fa fa-fw fa fa-question-circle"></i> Anasayfa Yönetimi </a>
                    </li>
                    <li>
                        <a href="@Url.Action("FileUpload","Admin")"><i class="fa fa-fw fa fa-question-circle"></i> Dosya Yükleme </a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
        <div id="page-wrapper">
            <div class="container-fluid">
                <!-- Page Heading -->
                <div class="row" id="main">
                    <div class="col-sm-12 col-md-12 well" id="content">
                        <h1>Site Kontrol Paneli</h1>
                    </div>
                </div>
                <!-- /.row -->
            </div>
            @RenderBody()
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
    </div><!-- /#wrapper -->


    <script src="~/Content/frontend.min4f17.js"></script>
    <script src="~/Content/jquery-migrate.mincbb1.js"></script>
    <script src="~/Content/jquery.minae22.js"></script>

</body>
</html>